#################
### RUN MODEL ###
#################

# update desired input files according to those generated by initialise.R

input_file_x = "input0.csv"

lassa_fever(
  input_file = input_file_x,
  output_file = "output.csv",
  params = params,
  sims_per_catchment = 1,
  processes = 1,
  max_spillovers = 113000
)
